Purpose: 
	This is a pipeline script implementing the DenovoWEST workflow for evaluating the significance of gene-specific
	enrichment of de novo variants.

Usage: 
	dnv_west.pl [--in DNVTable] --conf Config --out OutDir

Notes: 
	DenovoWEST is an extension of traditional Poisson test of DNV enrichment. The test statistics for each gene 
	is weighted sum of observed DNVs. Weights represent our prior brief of pathogenicity for different classes of
	DNVs. In DDD 2019, they stratified genes based on sHet >=0.15 or <0.15 and presence of absence of MCR, and 
	derived postive predictive values (PPVs) for LGD and missense variants in each gene set as a function of CADD
	score bins. They then smoothed PPVs as a function of CADD score and gene set, and use them as weights. 
	Generally, variant weights can be a function of both gene and variant specific properties. Our implementation
	allows variant weight to be a function of one or more categorical variables and one continuous variable. 
	The enrichment is evaluated by comparing observed weighted sum statistics with simulations based on per-bp 
	mutation rates. 

	To increase power for genes enriched only for missense variants, DenovoWEST also runs enrichment test using 
	only missense variants, then combines the evidence from missense clustering test by DenovoNear. The final 
	DenovoWEST p-value is the minimum of p-value for enrichment of all variants, and p-value for combined enrichment 
	and clustering of missense variants. 

	The input DNVs to DenovoWEST are assumed to be independent mutation events. To avoid inflating the test statistics 
	and creating false recurrences for DenovoNear, mutations shared by twin or sibs are counted only once. For nearby 
	variants in the same individual, only one with most severe effect should be kept.  

Input/output:
	The inputs include an annotated DNV table, a variant weight lookup table (used by utils/lookup_varwt.pl), and 
	annotations of all possible SNVs in exome (generated by enum_cdssnvs.pl). All possible SNVs in exome should be 
	enumerated from the same set of genes and annotated in the same way as input DNVs, because variant weights will
	be annotated to all variants. Per-bp mutation rates are needed for enrichment test, they will be calculated 
	from the method specified in the config.

	The workflow will first lookup variants weights and split input DNVs by gene, then prepare tables of per-bp 
	mutation rates and weights for each gene with DNVs, then run enrichment test (for all and missense variants) 
	and clustering test (for missense only) for each gene in parallel. The results of each gene will be collected 
	and reformatted in the final step. It is possible to run DenovoWEST on multiple sub-groups of the entire sample. 
	When sample groups are defined in the config, there will be one final output for each sample group.

Dependencies:
	The modified DenovoWEST scripts is included in the pipeline directory. The script depends on csvtk in part for 
	generating intermediate files. DenovoNear should be installed from source (https://github.com/jeremymcrae/denovonear).